/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basedbiblioteca;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * by rbn
 * @author orihime
 */
public class ActualizarInformacion extends javax.swing.JFrame {
//crea arraylist   
public ArrayList<datosLibros> datox2 = new ArrayList<datosLibros>();
    /**
     * Creates new form ActualizarInformacion
     */
//crea la tabla
    DefaultTableModel Table1;
    int cont=0;
    public ActualizarInformacion() {
        initComponents();
        
        String dcab[]={"1 ISBN","2 Nomb libro","3 nomb edit","4 año public","5 # de pág","6 valor com","7 # copias","8 Ubic libros"};   
        String dat[][]={};
        Table1=new DefaultTableModel(dat, dcab);
        jTable1.setModel(Table1);
    }
public void export(){
    
    datosLibros nuevo;
    for(int i=0; i<datox2.size(); i++){
    nuevo=(datosLibros)datox2.get(i);
   
  mostrarDatos(nuevo);
    
    }
      }
      public void mostrarDatos(datosLibros nuevo){
        Table1.insertRow(cont, new Object[]{});
        Table1.setValueAt(nuevo.getIsbm(), cont, 0);
        Table1.setValueAt(nuevo.getNombreLibro(), cont, 1);
        Table1.setValueAt(nuevo.getNombreEditorial(), cont, 2);
        Table1.setValueAt(nuevo.getAñoPublicacion(), cont, 3);
        Table1.setValueAt(nuevo.getNroDpaginas(), cont, 4);
        Table1.setValueAt(nuevo.getValorDcompra(), cont, 5);
        Table1.setValueAt(nuevo.getNroDcopias(), cont, 6);
        Table1.setValueAt(nuevo.getUbicacionEstantes(), cont, 7);
        cont++;
   
    }
//guarda los datos a un txt
    public void guardartxt(){
       
    try {
      
        java.io.FileOutputStream archivo=new java.io.FileOutputStream ("datosLibros.txt");
        java.io.ObjectOutputStream objDatox=new java.io.ObjectOutputStream(archivo);
        objDatox.writeObject(datox2);
    
        
         
    }
    catch (Exception e){
    
    JOptionPane.showMessageDialog(null,"Error al guardar el archivo"); //genera el archivo
         
    }
    }
    //lee un txt
    public void leerarchi(){
      try{
          java.io.FileInputStream archivo= new   java.io.FileInputStream("datosLibros.txt");
          java.io.ObjectInputStream objDatox= new java.io.ObjectInputStream(archivo);
          datox2=(ArrayList<datosLibros>) objDatox.readObject();
          export();
          
      } 
    catch (Exception e){
    JOptionPane.showMessageDialog(null,"Error al abrir el archivo"); //genera el archivo
    }
    
         }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "1 ISBN", "2 Nomb libro", "3 nomb edit", "4 año public", "5 # de pág", "6 valor com", "7 # copias", "8 Ubic libros"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("actualizacion de informacion");

        jButton1.setText("cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(321, 321, 321))))
            .addGroup(layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        leerarchi();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        guardartxt();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarInformacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
